# Linguagem Utilizada para Desenvolver a Aplicação
language: php

# Versão que a aplicação suporta.
php:
  - 5.5
  - 5.6
  - 7.0



deploy:
  provider: heroku
  api-key: 
    secure: $Heroku_API_KEY
  app: clone-netflix-dio
  
