language: python
python:
- 3.8.5
sudo: required
install:
- pip install flask
script:
- python test.py

deploy:
  provider: heroku
  api_key: lCyqxGpWmnthhuBfjQJPXM12CyjbeL+Z3oKjVOKdgDm8aM7pN/C7C1PXChoVs6359r1akKqOVQFjWJqaY9o3ka5J50vmgKoxnfqGge2L3s35cbsutuRBf+b6PDkYJNbgYwht4VeMQCadHcyVrJUVyEAVTPRSQTy59RnsaBPqfxW65htLco3+erMwmGk18SpdC/Z4z1wm4HrVFWKR47EoES2v2VPSvBqghopy0cCRrKuEMmvw77GrLD2SotxEdVsd2oATxXXvM3zhuC7Kkcz1OtQuhERCClLUJUN59epYaLLX2tihlaq5cS0TYzIEw/Ncq7+uAOGi4XT5WrwjHnrXh2OuYUjM4h7lw+dHPlLQi6q8jRSVXhAbS635Dw/dclSMkRJGxBxB229VJa0/xdKmvgAFqaNFwGV+LY09m4xu7evRnhIJYV1d9rEipMCSn5LBDheDLcG9J5OP0PE2XFMHjuDfZEmcxAdy8Tx0mqYSDOpZmF9UcBPhSYQROJsfFKjpkDsMOcpFcb+Y7gFAkiyOHk9xiVFZPpGC8Fi7mhO5cGQ38PrCf4TN8gV4s6yiX5YmJWntpYEVKghThmvoBeRC0TnO08boFrcZVCkNQ+Fqm/8q3E2DBcS+C2XVlxPmdz0YVRc7JFBryUcpmJJWFYz9DLfZESG3FsgdGLU/paf31js=
    app: netflix-clone-dio

