# Linguagem Utilizada para Desenvolver a Aplicação
language: php

# Versão que a aplicação suporta.
php:
  - "7"


# Defini que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku


deploy:
  provider: heroku
  api-key: 
    secure: $Heroku_API_KEY
  app: clone-netflix-dio
  
