# Linguagem Utilizada para Desenvolver a Aplicação
language: php

# Versão que a aplicação suporta.
php:
  - "7"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main

# Defini que o processo de Deploy será na Plataforma Heroku. É necessário informar o nome da APP criada no Heroku
deploy:
  provider: heroku
  api-key: 
    secure: $Heroku_API_KEY
  app: well87